#!/usr/bin/env node
/* ────────────────────────────────────────────────────────────
   Portfolio Factory — Niche Build Script

   Usage:
     node scripts/build-niche.js <profile> <niche>
     node scripts/build-niche.js shreyansh-singh dev
     node scripts/build-niche.js shreyansh-singh shopify
     node scripts/build-niche.js --all shreyansh-singh    (builds all niches)

   What it does:
     1. Reads profile JSON (personal data)
     2. Reads niche JSON (career data)
     3. Generates src/data/index.ts merging both
     4. Runs vite build
     5. Outputs to dist-{niche}/ folder
   ──────────────────────────────────────────────────────────── */

import { readFileSync, writeFileSync, existsSync, mkdirSync, cpSync, rmSync } from 'fs';
import { execSync } from 'child_process';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, '..');

// ─── Parse args ─────────────────────────────────────────────
const args = process.argv.slice(2);

if (args[0] === '--list') {
  const { readdirSync } = await import('fs');
  console.log('\n  Profiles:');
  readdirSync(join(ROOT, 'src/data/profiles')).filter(f => f.endsWith('.json')).forEach(f => {
    console.log(`    - ${f.replace('.json', '')}`);
  });
  console.log('\n  Niches:');
  readdirSync(join(ROOT, 'src/data/niches')).filter(f => f.endsWith('.json')).forEach(f => {
    console.log(`    - ${f.replace('.json', '')}`);
  });
  process.exit(0);
}

if (args.length < 2) {
  console.log(`
  Portfolio Factory — Build Script

  Usage:
    node scripts/build-niche.js <profile> <niche>
    node scripts/build-niche.js shreyansh-singh shopify
    node scripts/build-niche.js --all shreyansh-singh
    node scripts/build-niche.js --list

  Available profiles: Check src/data/profiles/*.json
  Available niches:   Check src/data/niches/*.json
  `);
  process.exit(1);
}

const buildAll = args[0] === '--all';
const profileName = buildAll ? args[1] : args[0];
const nicheName = buildAll ? null : args[1];

// ─── Load profile ───────────────────────────────────────────
const profilePath = join(ROOT, 'src/data/profiles', `${profileName}.json`);
if (!existsSync(profilePath)) {
  console.error(`Profile not found: ${profilePath}`);
  process.exit(1);
}
const profile = JSON.parse(readFileSync(profilePath, 'utf-8'));

// ─── Build function ─────────────────────────────────────────
function buildNiche(niche) {
  const nichePath = join(ROOT, 'src/data/niches', `${niche}.json`);
  if (!existsSync(nichePath)) {
    console.error(`Niche not found: ${nichePath}`);
    return false;
  }

  const nicheData = JSON.parse(readFileSync(nichePath, 'utf-8'));

  console.log(`\n  Building: ${profile.name} — ${nicheData.nicheLabel}`);
  console.log(`  Profile:  ${profileName}`);
  console.log(`  Niche:    ${niche}`);
  console.log(`  ${'─'.repeat(50)}`);

  // Generate src/data/index.ts
  const indexTs = generateIndexTs(profile, nicheData);
  const indexPath = join(ROOT, 'src/data/index.ts');

  // Backup original
  const backupPath = join(ROOT, 'src/data/index.ts.backup');
  if (existsSync(indexPath)) {
    cpSync(indexPath, backupPath);
  }

  try {
    writeFileSync(indexPath, indexTs, 'utf-8');
    console.log('  Generated src/data/index.ts');

    // Build
    console.log('  Running vite build...');
    execSync('npm run build', { cwd: ROOT, stdio: 'inherit' });

    // Copy dist to dist-{niche}
    const outDir = join(ROOT, `dist-${niche}`);
    if (existsSync(outDir)) rmSync(outDir, { recursive: true });
    cpSync(join(ROOT, 'dist'), outDir, { recursive: true });
    console.log(`  Output: dist-${niche}/`);

    // Update registry
    updateRegistry(profileName, niche, nicheData);

    console.log(`  Build complete for "${niche}" niche`);
    return true;
  } finally {
    // Restore original
    if (existsSync(backupPath)) {
      cpSync(backupPath, indexPath);
      rmSync(backupPath);
    }
  }
}

// ─── Generate index.ts from profile + niche ─────────────────
function generateIndexTs(profile, niche) {
  return `// Auto-generated by build-niche.js — DO NOT EDIT MANUALLY
// Profile: ${profile.name} | Niche: ${niche.nicheId}
// Generated: ${new Date().toISOString()}

export const profile = {
  name: ${JSON.stringify(profile.name)},
  initials: ${JSON.stringify(profile.initials)},
  title: ${JSON.stringify(niche.title)},
  tagline: ${JSON.stringify(niche.tagline)},
  bio: ${JSON.stringify(niche.bio)},
  email: ${JSON.stringify(profile.email)},
  phone: ${JSON.stringify(profile.phone)},
  location: ${JSON.stringify(profile.location)},
};

export const stats = ${JSON.stringify(niche.stats, null, 2)};

export const skills = ${JSON.stringify(niche.skills, null, 2)};

export const techStack = ${JSON.stringify(niche.techStack, null, 2)};

export const experience = ${JSON.stringify(niche.experience, null, 2)};

export const projects = ${JSON.stringify(niche.projects, null, 2)};

export const education = ${JSON.stringify(profile.education, null, 2)};

export const awards = ${JSON.stringify(niche.awards, null, 2)};

export const certifications = ${JSON.stringify(profile.certifications, null, 2)};

export const testimonials = ${JSON.stringify(niche.testimonials, null, 2)};

export const fiverrStats = ${JSON.stringify(niche.fiverrStats, null, 2)};

export const fiverrReviews = ${JSON.stringify(niche.fiverrReviews, null, 2)};

export const youtube = ${JSON.stringify(niche.youtube, null, 2)};

export const processSteps = ${JSON.stringify(niche.processSteps, null, 2)};

export const pricingPlans = ${JSON.stringify(niche.pricingPlans, null, 2)};

export const caseStudy = ${JSON.stringify(niche.caseStudy, null, 2)};
`;
}

// ─── Update deployment registry ─────────────────────────────
function updateRegistry(profileName, niche, nicheData) {
  const registryPath = join(ROOT, 'src/data/registry.json');
  let registry = { owner: profileName, deployments: [] };

  if (existsSync(registryPath)) {
    registry = JSON.parse(readFileSync(registryPath, 'utf-8'));
  }

  const slug = profileName.replace(/\s+/g, '-').toLowerCase();
  const id = `${slug}-${niche}`;
  const subdomain = `${slug}-${niche}`;

  const existing = registry.deployments.findIndex(d => d.id === id);
  const deployment = {
    id,
    profileRef: profileName,
    nicheRef: niche,
    subdomain,
    url: `https://${subdomain}.vercel.app`,
    status: 'built',
    lastBuilt: new Date().toISOString(),
    nicheLabel: nicheData.nicheLabel,
  };

  if (existing >= 0) {
    registry.deployments[existing] = deployment;
  } else {
    registry.deployments.push(deployment);
  }

  writeFileSync(registryPath, JSON.stringify(registry, null, 2), 'utf-8');
}

// ─── Execute ────────────────────────────────────────────────
if (buildAll) {
  const { readdirSync } = await import('fs');
  const niches = readdirSync(join(ROOT, 'src/data/niches'))
    .filter(f => f.endsWith('.json'))
    .map(f => f.replace('.json', ''));

  console.log(`\n  Building ALL ${niches.length} niches for ${profile.name}...`);

  let success = 0;
  for (const n of niches) {
    if (buildNiche(n)) success++;
  }

  console.log(`\n  Done! ${success}/${niches.length} niches built successfully.`);
} else {
  buildNiche(nicheName);
}
